### ISSUE TITLE
[7.0.8] 500 Internal Server Error となる

### ISSUE THREAD

**Issue by kometchtech** [weseek/growi-docker-compose#74]
## 症状

- アップデート手順に従って、containerイメージを更新、起動したところ、`500 Internal Server Error`となりGROWIを使用できない。

![image](https://github.com/weseek/growi-docker-compose/assets/5137077/5b835c30-6b97-4a8e-913e-ffd0a36e3223)

## 期待する結果

- 起動する。

## log

```
app-1  | {"name":"growi","hostname":"6461aa566b31","pid":15,"level":50,"msg":"Unhandled Rejection: Promise: Promise {\n  <rejected> Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@codemirror/state' imported from /opt/growi/apps/app/.next/server/pages/[[...path]].js\n      at packageResolve (node:internal/modules/esm/resolv
e:854:9)\n      at moduleResolve (node:internal/modules/esm/resolve:927:18)\n      at defaultResolve (node:internal/modules/esm/resolve:1157:11)\n      at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12)\n      at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25)\n      at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:227:38)\n      at ModuleLoader.import (node:internal/modules/esm/loader:315:34)\n      at defaultImportModuleDynamically (no
de:internal/modules/esm/utils:194:31)\n      at importModuleDynamicallyCallback (node:internal/modules/esm/utils:216:12)\n      at 26939 (/opt/growi/apps/app/.next/server/pages/[[...path]].js:1:34693) {\n    code: 'ERR_MODULE_NOT_FOUND'\n  },\n  [Symbol(webpack exports)]: { v: [Getter] },\n  [Symbol(webpack queues)]: [Function
 (anonymous)],\n  [Symbol(webpack error)]: Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@codemirror/state' imported from /opt/growi/apps/app/.next/server/page
s/[[...path]].js\n      at packageResolve (node:internal/modules/esm/resolve:854:9)\n      at moduleResolve (node:internal/modules/esm/resolve:927:18)\n      at defaultResolve (node:internal/modules/esm/resolve:1157:11)\n      at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12)\n      at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25)\n      at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:227:38)\n      at ModuleLoader.import (node:inter
nal/modules/esm/loader:315:34)\n      at defaultImportModuleDynamically (node:internal/modules/esm/utils:194:31)\n      at importModuleDynamicallyCallback (node:internal/modules/esm/utils:216:12)\n      at 26939 (/opt/growi/apps/app/.next/server/pages/[[...path]].js:1:34693) {\n    code: 'ERR_MODULE_NOT_FOUND'\n  }\n} Reason: 
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@codemirror/state' imported from /opt/growi/apps/app/.next/server/pages/[[...path]].js\n    at packageResolve (no
de:internal/modules/esm/resolve:854:9)\n    at moduleResolve (node:internal/modules/esm/resolve:927:18)\n    at defaultResolve (node:internal/modules/esm/resolve:11
57:11)\n    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12)\n    at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25)\n    at 
ModuleLoader.getModuleJob (node:internal/modules/esm/loader:227:38)\n    at ModuleLoader.import (node:internal/modules/esm/loader:315:34)\n    at defaultImportModul
eDynamically (node:internal/modules/esm/utils:194:31)\n    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:216:12)\n    at 26939 (/opt/growi/app
s/app/.next/server/pages/[[...path]].js:1:34693) {\n  code: 'ERR_MODULE_NOT_FOUND'\n}","time":"2024-05-30T16:47:21.137Z","v":0}                    
app-1  | {"name":"growi","hostname":"6461aa566b31","pid":15,"level":50,"msg":"Unhandled Rejection: Promise: Promise {\n  <rejected> Error [ERR_MODULE_NOT_FOUND]: Ca
nnot find package '@codemirror/state' imported from /opt/growi/apps/app/.next/server/pages/[[...path]].js\n      at packageResolve (node:internal/modules/esm/resolv
e:854:9)\n      at moduleResolve (node:internal/modules/esm/resolve:927:18)\n      at defaultResolve (node:internal/modules/esm/resolve:1157:11)\n      at ModuleLoa
der.defaultResolve (node:internal/modules/esm/loader:383:12)\n      at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25)\n      at ModuleLoader.getModu
leJob (node:internal/modules/esm/loader:227:38)\n      at ModuleLoader.import (node:internal/modules/esm/loader:315:34)\n      at defaultImportModuleDynamically (no
de:internal/modules/esm/utils:194:31)\n      at importModuleDynamicallyCallback (node:internal/modules/esm/utils:216:12)\n      at 26939 (/opt/growi/apps/app/.next/
server/pages/[[...path]].js:1:34693) {\n    code: 'ERR_MODULE_NOT_FOUND'\n  },\n  [Symbol(webpack exports)]: Object [Module] {\n    copyLineDown: [Getter],\n    cop
yLineUp: [Getter],\n    cursorCharLeft: [Getter],\n    cursorCharRight: [Getter],\n    cursorDocEnd: [Getter],\n    cursorDocStart: [Getter],\n    cursorGroupLeft: 
[Getter],\n    cursorGroupRight: [Getter],\n    cursorLineBoundaryBackward: [Getter],\n    cursorLineBoundaryForward: [Getter],\n    cursorLineBoundaryLeft: [Getter
],\n    cursorLineBoundaryRight: [Getter],\n    cursorLineDown: [Getter],\n    cursorLineEnd: [Getter],\n    cursorLineStart: [Getter],\n    cursorLineUp: [Getter],
\n    cursorMatchingBracket: [Getter],\n    cursorPageDown: [Getter],\n    cursorPageUp: [Getter],\n    cursorSyntaxLeft: [Getter],\n    cursorSyntaxRight: [Getter]
,\n    defaultKeymap: [Getter],\n    deleteCharBackward: [Getter],\n    deleteCharForward: [Getter],\n    deleteGroupBackward: [Getter],\n    deleteGroupForward: [G
etter],\n    deleteLine: [Getter],\n    deleteToLineEnd: [Getter],\n    deleteToLineStart: [Getter],\n    emacsStyleKeymap: [Getter],\n    indentLess: [Getter],\n  
  indentMore: [Getter],\n    indentSelection: [Getter],\n    indentWithTab: [Getter],\n    insertBlankLine: [Getter],\n    insertNewlineAndIndent: [Getter],\n    mo
veLineDown: [Getter],\n    moveLineUp: [Getter],\n    selectAll: [Getter],\n    selectCharLeft: [Getter],\n    selectCharRight: [Getter],\n    selectDocEnd: [Getter
],\n    selectDocStart: [Getter],\n    selectGroupLeft: [Getter],\n    selectGroupRight: [Getter],\n    selectLine: [Getter],\n    selectLineBoundaryBackward: [Gett
er],\n    selectLineBoundaryForward: [Getter],\n    selectLineBoundaryLeft: [Getter],\n    selectLineBoundaryRight: [Getter],\n    selectLineDown: [Getter],\n    se
lectLineEnd: [Getter],\n    selectLineStart: [Getter],\n    selectLineUp: [Getter],\n    selectPageDown: [Getter],\n    selectPageUp: [Getter],\n    selectParentSyn
tax: [Getter],\n    selectSyntaxLeft: [Getter],\n    selectSyntaxRight: [Getter],\n    simplifySelection: [Getter],\n    splitLine: [Getter],\n    standardKeymap: [
Getter],\n    toggleBlockComment: [Getter],\n    toggleBlockCommentByLine: [Getter],\n    toggleComment: [Getter],\n    toggleLineComment: [Getter],\n    transposeC
hars: [Getter]\n  },\n  [Symbol(webpack queues)]: [Function (anonymous)],\n  [Symbol(webpack error)]: Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@codemirror
/state' imported from /opt/growi/apps/app/.next/server/pages/[[...path]].js\n      at packageResolve (node:internal/modules/esm/resolve:854:9)\n      at moduleResol
ve (node:internal/modules/esm/resolve:927:18)\n      at defaultResolve (node:internal/modules/esm/resolve:1157:11)\n      at ModuleLoader.defaultResolve (node:inter
nal/modules/esm/loader:383:12)\n      at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25)\n      at ModuleLoader.getModuleJob (node:internal/modules/e
sm/loader:227:38)\n      at ModuleLoader.import (node:internal/modules/esm/loader:315:34)\n      at defaultImportModuleDynamically (node:internal/modules/esm/utils:
194:31)\n      at importModuleDynamicallyCallback (node:internal/modules/esm/utils:216:12)\n      at 26939 (/opt/growi/apps/app/.next/server/pages/[[...path]].js:1:
34693) {\n    code: 'ERR_MODULE_NOT_FOUND'\n  }\n} Reason: Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@codemirror/state' imported from /opt/growi/apps/app/.
next/server/pages/[[...path]].js\n    at packageResolve (node:internal/modules/esm/resolve:854:9)\n    at moduleResolve (node:internal/modules/esm/resolve:927:18)\n
    at defaultResolve (node:internal/modules/esm/resolve:1157:11)\n    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12)\n    at ModuleLoader
.resolve (node:internal/modules/esm/loader:352:25)\n    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:227:38)\n    at ModuleLoader.import (node:int
ernal/modules/esm/loader:315:34)\n    at defaultImportModuleDynamically (node:internal/modules/esm/utils:194:31)\n    at importModuleDynamicallyCallback (node:inter
nal/modules/esm/utils:216:12)\n    at 26939 (/opt/growi/apps/app/.next/server/pages/[[...path]].js:1:34693) {\n  code: 'ERR_MODULE_NOT_FOUND'\n}","time":"2024-05-30
T16:47:21.137Z","v":0}                   
app-1  | Yjs was already imported. This breaks constructor checks and will lead to issues! - https://github.com/yjs/yjs/issues/438                                  
app-1  |  ⨯ Error: Cannot find module 'react-dropzone'                            
app-1  | Require stack:                  
app-1  | - /opt/growi/apps/app/.next/server/pages/[[...path]].js                  
app-1  | - /opt/growi/node_modules/next/dist/server/require.js                    
app-1  | - /opt/growi/node_modules/next/dist/server/next-server.js                
app-1  | - /opt/growi/node_modules/next/dist/server/next.js                       
app-1  | - /opt/growi/apps/app/dist/server/crowi/index.js                         
app-1  | - /opt/growi/apps/app/dist/server/app.js                                 
app-1  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)                                                                                  
app-1  |     at /opt/growi/node_modules/next/dist/server/require-hook.js:55:36                                                                                      
app-1  |     at Module._load (node:internal/modules/cjs/loader:986:27)            
app-1  |     at Module.require (node:internal/modules/cjs/loader:1233:19)                                                                                           
app-1  |     at mod.require (/opt/growi/node_modules/next/dist/server/require-hook.js:65:28)                                                                        
app-1  |     at require (node:internal/modules/helpers:179:18)                    
app-1  |     at 56358 (/opt/growi/apps/app/.next/server/pages/[[...path]].js:1:32490)                                                                               
app-1  |     at t (/opt/growi/apps/app/.next/server/webpack-runtime.js:1:128)                                                                                       
app-1  |     at 98768 (/opt/growi/apps/app/.next/server/chunks/1340.js:1:27941)                                                                                     
app-1  |     at t (/opt/growi/apps/app/.next/server/webpack-runtime.js:1:128) {                                                                                     
app-1  |   code: 'MODULE_NOT_FOUND',     
app-1  |   requireStack: [               
app-1  |     '/opt/growi/apps/app/.next/server/pages/[[...path]].js',             
app-1  |     '/opt/growi/node_modules/next/dist/server/require.js',               
app-1  |     '/opt/growi/node_modules/next/dist/server/next-server.js',           
app-1  |     '/opt/growi/node_modules/next/dist/server/next.js',                  
app-1  |     '/opt/growi/apps/app/dist/server/crowi/index.js',                    
app-1  |     '/opt/growi/apps/app/dist/server/app.js'                             
app-1  |   ]                             
app-1  | }          
```

**Comment by yuki-takei** [comment]
@kometchtech ご報告ありがとうございます。v7.0.8 の公式イメージは使えないようです。
修正して v7.0.9 をリリースしますのでしばらくお待ちください。

**Comment by kometchtech** [comment]
v7.0.9では問題ないことを確認しました。
素早いご対応ありがとうございました。
